### ISSUE TITLE
Feature request: object prefix syntax. 

### ISSUE THREAD

**Issue by TeffenEllis** [smyte/jsxstyle#102]
Howdy,

I'm a big fan of JSX Style, though the prefixes for pseudo-elements and selectors props can be quite cumbersome for multiple styles. This can be especially difficult if the pseudo-element styles are set with another prop. I've gotten around this limitation by creating style objects with a helper function that prefixes each key with a string:

```javascript
const baseStyle = {
  color: colors.linkBlue,
  textDecoration: 'none',
  ...prefixKeys('hover', {
    color: colors.linkOrange,
    cursor: 'pointer'
  }),
  ...prefixKeys('before', {
    content: '"foo"',
    position: 'absolute',
    display: 'block',
    pointerEvents: 'none',
    ...prefixKeys('hover', {
      content: '"bar"'
    })
  })
}

return <Block {...baseStyle} />
```

It'd be interesting if these styles could also be expressed as nested objects:

```javascript
const baseStyle = {
  color: colors.linkBlue,
  textDecoration: 'none',
  hover: {
    color: colors.linkOrange,
    cursor: 'pointer'
  },
  before: {
    content: '"foo"',
    position: 'absolute',
    display: 'block',
    pointerEvents: 'none',
    hover: {
      content: '"bar"'
    }
  }
}

return <Block {...baseStyle} />
```

Cheers 🍻

**Comment by meyer** [comment]
Thanks for the suggestion, @TeffenEllis. The primary reason we use a flat prop structure is so that objects of styles can be easily merged, either with the spread syntax feature of JSX or with `Object.assign`.

At Smyte, we keep common objects of styles in a separate file and apply them where they’re needed throughout the codebase. Using spread syntax and style props ordered intentionally, we can apply a general set of styles to a thing and then customise specific style properties that the general set applied. However, if our style groups contained nested groups, that style prop pinpointing would be impossible without the use of a deep merge utility function every place we currently use spread syntax.

Do you have a specific concern about prefixed style names, or is your concern mainly around syntax? I’d be more inclined to give syntax a rethink if moving to nested object syntax enabled us to add some neat new features to jsxstyle.

**Comment by meyer** [comment]
I explained the combined spreads thing a bit more clearly in a different issue: https://github.com/smyte/jsxstyle/issues/70#issuecomment-321469374

**Comment by TeffenEllis** [comment]
Howdy @meyer,

Thanks for the update and explanation. Your usage of spread syntax can be extremely powerful, especially with [higher order components](https://github.com/cloudflare-apps/sable/blob/master/source/components/link/link.tsx#L64-L87)! I've found that this aligns with existing concepts in CSS and JavaScript. I believe allowing `before`, `after`, `hover` and other properties prop objects can help align these concepts even further 😄

**Comment by meyer** [comment]
@TeffenEllis I know I’m a bit biased but I do prefer the former 😀. While the existing prefix pattern may feel a bit repetitive, it allows for a lot more flexibility with fewer lines of code (in the case of the example you posted, half as many LOC) and it encourages patterns of reuse that we would like to see more developers adopt. Moving pseudo styles to object syntax would reduce flexibility for nothing more than a syntax change. To me it’s not worth it.

I would consider a major syntax change such as this one if a) the existing pattern was confusing or revealed itself to be a fundamentally bad design decision, and if b) the suggested replacement syntax was a _vast improvement_ over the former syntax. In this case, it’s a lateral move, and for some users (myself included) would be a step backwards. I’m going to keep pseudo syntax as is for now, but will keep this issue in mind as we move forward.

Do note that I’m not opposed to object syntax in jsxstyle props. We only use object syntax in one place right now and I feel like there are [many more places](https://github.com/smyte/jsxstyle/issues/71#issue-250052774) we can use it. I just don’t think pseudoelement/pseudoclass syntax is the right place.

Hope that makes sense. Thanks again for the suggestion.
