### ISSUE TITLE
Naming fatigue when reusing css styles.

### ISSUE THREAD

**Issue by chenxsan** [smyte/jsxstyle#113]
This is just a question.

I choose jsxstyle over styled-components for less naming fatigue, but when I try to reuse some styles under jsxstyle, I found myself having naming fatigue again.

Here's how I reuse css styles at first:

```
import { bps } from '../constants'
import { Block } from 'jsxstyle'
import React from 'react'
import PropTypes from 'prop-types'
const ArticleHeader = ({ children }) => (
  <Block
    marginBottom='1em'
    component='header'
    mediaQueries={bps}
    smMarginBottom='3em'
  >
    {children}
  </Block>
)
export default ArticleHeader
ArticleHeader.propTypes = {
  children: PropTypes.node.isRequired
}
```
Oh, file named `ArticleHeader.js`.

Then I found that I can actually make a style object and spread it like:

```
const articleHeaderStyle = {
  marginBottom: '1em',
  mediaQueries: bps,
  smMarginBottom: '3em'
}
<Block {...articleHeaderStyle}>some wrapped contents</Block>
```
Again, I need to name `articleHeaderStyle`.

I'm wondering if these naming are possible to eliminate in jsxstyle :)

**Comment by meyer** [comment]
Good question! At the end of the day, _something_ is going to need to be named, but since one component can be styled by many style objects, style object names don’t need to map directly to the components they’re styling.

At Smyte, we use a combination of primitive reusable components and small reusable style objects named by _feature_ (`focusStyles`) as opposed to implementation (`userSearchInputFocusStyles`). For primitive components that might need slightly different styles based on where they’re used, we pass through the necessary style props.

The example you posted is pretty close to what we do—`ArticleHeader` is a primitive reusable component and `articleHeaderStyle` is a reusable style object. `articleHeaderStyle` could be named in a way that’s more descriptive of what that style object _does_. I know that doesn’t entirely solve the problem of naming fatigue, but I’ve found that it’s much easier to name small style objects according to the style changes the apply than it is to name mundane components according to their function on the page. Bonus: you can be as verbose as you need with style object names since the style objects themselves will either be minified or completely inlined with `jsxstyle-loader`.

---

On a related note, if you’ve got any feedback on or suggestions for the media query feature I’d love to hear it. We built it for a very specific use case but there’s a lot of room for improvement.

**Comment by meyer** [comment]
In practice I’ve found that we don’t reuse a lot of our reusable style objects, and the ones we do reuse are style groups that have been reverse-engineered from styles we found ourselves applying many times over, like the a11y styles I mentioned above. I end up using single constants a lot more often than I do groups of styles.

For context, my approach to writing CSS is rather designer-y—that is to say, I nudge things along pixel by pixel until they’re where I want them to be. As a result, my CSS ends up being a bit more specific than it would if I was reusing lots of style objects.

My least favourite thing with writing CSS is when I reach the point where I can no longer keep the entire system in my head. That problem is something we’ve explicitly tried to avoid with jsxstyle. If the end result of jsxstyle was a pile of JS files full of object-syntax CSS, it would provide very little benefit over plain old CSS.

The trick is balance, I think. If you’re finding that you’re grow weary of naming things, perhaps you can group smaller named components into larger ones. Our objective with having a few generic stylable primitives is to save you from naming fatigue, not to reinvent it 😀

Anyways. Hope that makes sense.

**Comment by chenxsan** [comment]
Thanks for sharing.

Balance is obviously difficult :)

I'll post it when I have any feedback for media query.
