### ISSUE TITLE
Offload autoprefixing to an existing library

### ISSUE THREAD

**Issue by py-in-the-sky** [smyte/jsxstyle#17]
Would this work instead?  https://github.com/postcss/postcss-js

If you haven't already considered this and it seems like something interesting and useful to you, I'm willing to test it and make a PR to include it.

**Comment by meyer** [comment]
this looks like an interesting prefixing option as well: https://github.com/rofrischmann/inline-style-prefixer

**Comment by meyer** [comment]
@py-in-the-sky we’re [working on making the autoprefixer injectable](https://github.com/smyte/jsxstyle/commit/ec18fca37cd8747925222d86d1c24164a0fe1326) so you can drop in a CSS postprocessor of your choosing.

**Comment by moimael** [comment]
It seems to be merged, is the use of this documented somewhere ?

**Comment by meyer** [comment]
@moimael it’s not documented yet, but I’m redoing the example at the moment and will be updating the documentation as well.

**Comment by meyer** [comment]
@py-in-the-sky @moimael at long last, an update! I’m so sorry for the lack of communication on this issue.

I thought quite a bit about how best to implement a runtime autoprefixer. Quite a few options exist already, but I really hate the idea of shipping a function to the client that generates the same basic thing over and over again. Really, I want the power and flexibility of a comprehensive autoprefixing system like `autoprefixer` but I don’t want to force people to have to download that system and then run it _every time_ they visit a thing that uses `jsxstyle`. I’ve come up with something that I think is a much more elegant solution to this problem.

I’ve been working on [jsxstyle-loader][loader], a webpack loader that extracts _static styles_ from `jsxstyle` elements and runs them through whatever CSS loaders you specify. I think it’s far better than autoprefixing at runtime, and I hope you’ll find it useful. You can read more about it in the [`jsxstyle-loader` README][readme], but I’ll write a brief summary here as well.

At compile time, when `jsxstyle-loader` encounters a component that contains `jsxstyle` elements with _static values_ (number, string, or value from a whitelisted source), it’ll create a virtual sidecar CSS file that contains those static styles. It’ll also add a `require()` to the top of your component file that points to the sidecar CSS file. You can then specify whatever CSS loaders you want in your webpack config, and the CSS will be processed however you choose. For me, I use `postcss-loader` with `postcss-cssnext` to autoprefix.

The only drawback is that dynamic values will _not_ be autoprefixed since they will be left on the `jsxstyle` element. I’m using the loader on several big projects right now and I haven’t yet run into this issue, but I’m interested to see if/when it’ll crop up.

`jsxstyle-loader` is (obviously) webpack-only, but the transforms use babel and the core of the loader could quite easily be used in a babel plugin, no webpack required. Still under consideration.

Let me know if you have any questions.

[loader]: https://github.com/smyte/jsxstyle-loader
[readme]: https://github.com/smyte/jsxstyle-loader#readme
