### ISSUE TITLE
Move to Smyte org action items

### ISSUE THREAD

**Issue by petehunt** [smyte/jsxstyle#38]
- [x] Injectable autoprefixer (@petehunt)
- [x] Version → 1.0 (@petehunt)
- [x] Make clear that the webpack loader is experimental (@petehunt / @meyer)
- [x] New, simplified docs (@petehunt / @meyer)
- [x] `LICENSE` (Apache 2) (@petehunt)
- [x] Roadmap (@petehunt / @meyer): https://github.com/smyte/jsxstyle/projects/1

**Comment by hnordt** [comment]
I would like to be a contributor.

**Comment by meyer** [comment]
@hnordt we’re working on the roadmap at the moment. Once it’s done it’ll be a good place to see areas where you can contribute. In the mean time, feel free to open issue or submit a PR if there’s a feature that you’d like to see.

**Comment by natew** [comment]
Any update on roadmap? Mostly curious: will a lot change API-wise in next version?

**Comment by meyer** [comment]
@natew the API will remain the same; updates to jsxstyle will build on the existing API.

Honestly, I’ve had a hard time coming up with a roadmap because jsxstyle is pretty close to what we need both at Smyte and in my personal React projects. As far as what’s next: I’d like to put some effort into performance and reliability. We do a few sensible things, like garbage collecting unused styles, but I’d like to make sure we’re doing everything we can to ensure that jsxstyle does what it needs to do as quickly as possible.

I’ve created [a Github project for jsxstyle 2.0 features][2.0]. If you’ve got any ideas you’d like to share, feel free to add them here or in a new issue.

[2.0]: https://github.com/smyte/jsxstyle/projects/1
