### ISSUE TITLE
Conditional rendering attribute

### ISSUE THREAD

**Issue by StokeMasterJack** [smyte/jsxstyle#47]
I know there is already a way to do this using javascript. But sometimes it would be just cleaner to do this:

<Block show={isAdmin}>
     Click Me
     Click Me
     Click Me
     Click Me
</Block>

I figure if the show attribute is omitted, it defaults to true.

**Comment by meyer** [comment]
@StokeMasterJack since jsxstyle is primarily focused on styling React components, conditional rendering is a bit out of scope. Conditional rendering can be done quite a few different ways. At Smyte we tend to separate out conditionally-rendered elements from the main return value of `render` and set the variable value to something if the required conditions are met:

```jsx
let adminOnlyThing = null;

if (isAdmin) {
  adminOnlyThing = <AdminThing />;
}

return (
  <Block>{adminOnlyThing}</Block>
);
```

Hope that makes sense.
