### ISSUE TITLE
RFC: Use arrays for media query values

### ISSUE THREAD

**Issue by jaredpalmer** [smyte/jsxstyle#70]
@meyer An idea for a more concise API for media queries:

## Current Behavior:

```jsx
<Block
  mediaQueries={{ sm: '(min-width:700px)',  lg: '(min-width: 1000px)' }}
  color="red"
  smColor="green"
  lgColor="blue"
  margin="2rem"
/>
```

## Desired Functionality:

```jsx
<Block
  mediaQueries={['(min-width: 400px)', '(min-width: 1000px)' ]}
  color={['red', 'blue', 'green']}
  margin="2rem"     // strings are still the cool
/>
```

**Comment by meyer** [comment]
@jaredpalmer I’ve seen this syntax in a few different CSS in JS libraries and I kind of dig it, but I went with the more explicit version for a few reasons:

1. we’ve got precedent for using prefixes. Doesn’t mean everything needs to fit into the prefix model but it’s a thing to consider when adding new features.
2. with separate props for each style prop, we get existing prop merging behaviour for freeeee (JSX spread syntax). Single props as arrays are nigh impossible to merge.
3. This is probably negligible, but I can [skip a check][] if the `mediaQueries` prop is not present. With the proposed array API I’d either have to do an array check for each prop or I’d have to do something hackier. I might be wrong about this though, as I don’t know all the tricks in the JS book.

More concisely put, the reason I like one prop per style value instead of props with potential array values is that you can keep style “features” somewhere else and then merge them all into one thing. Here’s a contrived example:

```jsx
import {styles, mediaQueries} from '../common/LayoutConstants';

<Block
  {...styles.button}
  {...styles.redButton}
  {...styles.smFullWidth}
  mediaQueries={mediaQueries}
  props={{type: 'button'}}
>
  Red button that’s full width on small screens
</Block>
```

[skip a check]: https://github.com/smyte/jsxstyle/blob/e6b25ee/src/getStyleKeysForProps.js#L90-L99

**Comment by jaredpalmer** [comment]
> with separate props for each style prop, we get existing prop merging behaviour for freeeee (JSX spread syntax). Single props as arrays are nigh impossible to merge.

Okay. You've convinced me.
