### ISSUE TITLE
Document `Box`

### ISSUE THREAD

**Issue by steadicat** [smyte/jsxstyle#76]
The `Box` component (unstyled `div`) is useful in some cases, for example for components where the `display` prop can be passed in or overridden by a parent. `Block` can cause a CSS conflict, with the `display: block` rule sometimes taking higher precedence. It would be nice if `Box` were mentioned in the readme.

**Comment by meyer** [comment]
@steadicat Since the initial styles applied to each primitive component are passed as `defaultProps`, the `display` property can always be overwritten or cleared.

```jsx
// clear the display prop
<Block display={null} />

// 😩
<Block display="flex" />
```

`Box` was intended to be a companion to `jsxstyle-loader` but I can see how it might be useful elsewhere. I’ll add it to the README.

**Comment by steadicat** [comment]
Cool. FWIW, I’m pretty sure I ran into a case where using `Block` instead of `Box` caused a `display: block` rule to be added which conflicted and took precedence. I think it was something like this:

```js
const Inner = props => <Block {...props} />;
const Outer = props => <Inner component={Inline} />;
```

**Comment by meyer** [comment]
Ha, this is wild. Yeah, in this case, since no actual props are set, `Block`’s default props are applied to the component specified in the `component` prop. `Inline`’s default props aren’t used since they’re already specified by the `Block`.

In the minimal example you’ve provided, it would be better to set `display` to `inline` than to set `component` to another `jsxstyle` component, but I’m not sure what the real-life case looks like.

**Comment by meyer** [comment]
Documented here: https://github.com/smyte/jsxstyle/blob/21e5127/packages/jsxstyle/README.md#hello-world-

Thanks @steadicat!
