### ISSUE TITLE
Does jsxstyle support `:before`?

### ISSUE THREAD

**Issue by chenxsan** [smyte/jsxstyle#77]
Looks like `beforeContent='content'` doesn't work:

```js
<Flex beforeContent='content'></Flex>
```

**Comment by meyer** [comment]
@chenxsan I added `:before` and `:after` support a few beta version ago, but I ended up removing it because of unexpected behaviour when passing empty strings as the value of the content property. Empty strings are falsey and are therefore not rendered in the final output CSS, but with the `content` property, sometimes an empty string _is_ the desired value.

I’m considering adding support back before 2.0 is released, though, but I’d need to special-case the `content` property.

Optionally, we could require the user to pass a twice-quoted string:

```jsx
<Block beforeContent="'both single and double quotes'" />
```

**Comment by meyer** [comment]
For reference, here’s the discussion around `:before`/`:after`: https://github.com/smyte/jsxstyle/commit/ae1658ae48a0130af608e475b350fe73fc364b7f#comments

**Comment by meyer** [comment]
For reference, here’s the discussion around `:before`/`:after`: https://github.com/smyte/jsxstyle/commit/ae1658ae48a0130af608e475b350fe73fc364b7f#comments

I actually forgot to make a TODO to add `:before`/`:after` support back. I’ll make a note now. Thanks for the reminder.

**Comment by chenxsan** [comment]
@meyer Thanks!

**Comment by meyer** [comment]
@chenxsan I’ve added `:before`/`:after` back to whitelisted pseudoelements. I haven’t (yet) added any special-case stuff to CSS generation, so empty strings will still cause the prop to not appear. For now, the workaround for empty strings is to use the quotes-inside-quotes hack I mentioned earlier.

Let me know if you run into anything funky with `:before`/`:after`.
