### ISSUE TITLE
jsxstyle-loader does not remove unused bindings after it runs

### ISSUE THREAD

**Issue by steadicat** [smyte/jsxstyle#82]
Testing `jsxstyle-loader` with TypeScript, I quickly ran into this issue.

See the comments here:
https://github.com/steadicat/jsxstyle-test/blob/c8779e956a5d705998a2263a39ceccd708ef339e/src/App.tsx

Basically it seems that the loader leaves around a few unused variables after it does its thing. This clashes with TypeScript compiler’s `noUnusedLocals` rule.

**Comment by steadicat** [comment]
If I turn off the `noUnusedLocals` rule, I get:

```
./src/App.tsx
(15,7): error TS2339: Property '_Box' does not exist on type 'JSX.IntrinsicElements'.
```

So it seems like the issue runs a little deeper than simply leaving around unused variables.

**Comment by meyer** [comment]
I did a bit of googling, and from what I can tell, `JSX.IntrinsicElements` contains all standard DOM element names. Typescript seems to be treating `_Box` like a DOM element instead of a component, and it’s complaining because it’s a non-standard DOM element. This is mostly a theory, but I’m going to test this in a bit with your demo project to make sure I’m understanding the error correctly.

As I mentioned in [your commit on `jsxstyle-test`][commit], I’ll look into generating a more component-y identifier for the `Box` import. I’m personally not a fan of that underscore prefix, but it’s what `babylon` gives by default.

Regarding `noUnusedLocals`, `jsxstyle-loader` will only remove `jsxstyle` imports. When it comes to mangling someone else’s code, I try to err on the safe side. I’d rather have `jsxstyle-loader` be slightly less effective than have it be 100% kickass but also breaking people’s builds. That said, I’ll look into some way of removing variable declarations that become unused as a result of `jsxstyle-loader` doing its thing. I might add it as an optional enhancement, or maybe farm it out to [`babel-plugin-minify-dead-code-elimination`][dce].

[commit]: https://github.com/steadicat/jsxstyle-test/commit/c8779e956a5d705998a2263a39ceccd708ef339e#commitcomment-25372522
[dce]: https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination

**Comment by meyer** [comment]
@steadicat I’ve removed the underscore prefix from the `Box` import as a workaround for TypeScript’s `JSX.IntrinsicElements` bug. Also opened a PR which should fix the bug (https://github.com/Microsoft/TypeScript/pull/19946).

I also added a trimmed down version of your example project to `/examples`. If you think of any ways the example could be improved, let me know!

I’m still trying to figure out a sensible and safe way to remove unused variables, but in the mean time, you’ll have to set `noUnusedLocals` to false 😕

**Comment by meyer** [comment]
I just had a thought: if unused variable checking was moved to the `tslint-loader`, you could add `jsxstyle-loader` as a `pre` loader, right after `tslint-loader`. Hmmmmm…

**Comment by meyer** [comment]
@steadicat I just added an (undocumented) `evaluateVars` option to `jsxstyle-loader`. Simple static style prop values like strings and numbers will be extracted, but anything that contains a variable will be left as is. This doesn’t solve the `noUnusedLocals` problem but it should make `noUnusedLocals` and `jsxstyle-loader` play together a bit more nicely.

When I get some time I’ll take a crack at an optional `removeUnusedVars` option that will check the number of references on items in scope and remove them if the reference count is zero.

**Comment by meyer** [comment]
Thought about this a bit more. There are one or two AST modifications that `jsxstyle-loader` does I’d consider unsafe/aggressive. This would be another one. Might need to add explicit opt-in config options—something like `unsafe: true` to enable all, or `unsafe: { /* options */ }` to cherry pick.

**Comment by meyer** [comment]
@steadicat now that I’ve famliarised myself a bit more with TypeScript and related tooling, I think I’ve figured out a decent workaround for this issue. The one downside is that `babel-loader` will be required in addition to `ts-loader`.

`ts-loader` needs to be set to **preserve JSX** and **preserve import syntax**. If you’ve been using webpack + TypeScript + tree shaking, import syntax should already be preserved (otherwise it won’t work). `jsxstyle-loader` should run _after_ `ts-loader` does its thing. `babel-loader` will handle JSX and webpack will handle import syntax.

Here’s a minimal example of the set of loaders required to do as I described:

```js
{
  test: /\.(?:js|tsx?)$/,
  exclude: /node_modules/,
  use: [
    // 3️⃣ transform JSX
    { loader: 'babel-loader' },
    // 2️⃣ extract styles
    { loader: 'jsxstyle-loader' },
  ],
},
{
  test: /\.tsx?$/,
  // 1️⃣ transpile TypeScript
  loader: 'ts-loader',
  options: {
    // I’m overriding compilerOptions in the webpack config so tsconfig.json
    //   is not webpack-specific.
    compilerOptions: {
      // ✅ preserve JSX
      jsx: 'preserve',
      // ✅ preserve import syntax
      // 'esnext' is 'es6' with import function syntax support as well
      module: 'esnext',
    },
  },
},
```

When you get a chance, try it out and let me know if it works for you.

**Comment by meyer** [comment]
@steadicat now that I’ve familiarised myself a bit more with TypeScript and related tooling, I think I’ve figured out a decent workaround for this issue. The one downside is that `babel-loader` will be required in addition to `ts-loader`.

`ts-loader` needs to be set to **preserve JSX** and **preserve import syntax**. If you’ve been using webpack + TypeScript + tree shaking, import syntax should already be preserved (otherwise it won’t work). `jsxstyle-loader` should run _after_ `ts-loader` does its thing. `babel-loader` will handle JSX and webpack will handle import syntax.

Here’s a minimal example of the set of loaders required to do as I described:

```js
{
  test: /\.(?:js|tsx?)$/,
  exclude: /node_modules/,
  use: [
    // 3️⃣ transform JSX
    { loader: 'babel-loader' },
    // 2️⃣ extract styles
    { loader: 'jsxstyle-loader' },
  ],
},
{
  test: /\.tsx?$/,
  // 1️⃣ transpile TypeScript
  loader: 'ts-loader',
  options: {
    // I’m overriding compilerOptions in the webpack config so tsconfig.json
    //   is not webpack-specific.
    compilerOptions: {
      // ✅ preserve JSX
      jsx: 'preserve',
      // ✅ preserve import syntax
      // 'esnext' is 'es6' with import function syntax support as well
      module: 'esnext',
    },
  },
},
```

When you get a chance, try it out and let me know if it works for you.

**Comment by meyer** [comment]
Update: turns out setting `module: 'esnext'` in your tsconfig is a better idea, since apparently setting `module` to `esnext` turns CommonJS requires (`import Thing = require('thing');`) into errors.
