### ISSUE TITLE
Pass DOM props through / classSet

### ISSUE THREAD

**Issue by petehunt** [smyte/jsxstyle#91]
What's jsxstyle's mission statement? Do we have one?

My suggestion would be something like: "jsxstyle is HTML as you wish it was in 2017" or something.

When using jsxstyle I often want to add event handlers, tabIndex etc to the styled elements. This has no ambiguity with the existing style props, so why not pass through non-style props to the DOM itself?

Additionally, if we're trying to make HTML as we wish it was, we could consider baking something like `classSet` into jsxstyle. It was originally baked into React and was later removed as too controversial.

**Comment by appsforartists** [comment]
Does this mean jsxstyle would need to include a whitelist of known CSS properties/browser prefixes?  Do you know what the bundle size impact of such a whitelist would be?

**Comment by meyer** [comment]
@appsforartists runtime jsxstyle is slightly under 3kb gzipped right now, so we’ve got room to grow if we have to, and a whitelist would gzip reasonably well. The way this discussion has gone in the past is less around bytes and more around whitelist maintenance and strictness of existing API.

@petehunt original discussion on attribute passthrough is on #32, but it’s been a while since it’s been discussed further. jsxstyle 3 would be a good opportunity to revisit some API decisions (see #90 and [more](https://github.com/smyte/jsxstyle/issues?q=is%3Aissue+is%3Aopen+label%3A%22feedback+requested%22)).

`classSet` would be interesting. In my experience I haven’t had to use many classnames with jsxstyle components (a selling point of jsxstyle IMO). If I have to use `classNames` it’s usually when integrating with a third-party thing, and then I have to deal with their global BEM’d extremely wordy class names. That said, my experience doesn’t speak for everyone. I’d be interested to hear other people’s experiences with class names and jsxstyle.

As far as mission statement goes… I’m not sure. jsxstyle 2 has been all about expanding what jsxstyle can do, both by extending the initial API and by building tooling for jsxstyle. The thing I like about jsxstyle is that I can _style as fast as I can think_ (well, as fast as my hands can type). That’s been the internal mission statement for me. I even put it [right near the top of the README](https://github.com/smyte/jsxstyle/tree/8fe99b2#%EF%B8%8F-style-as-fast-as-you-can-think).

I’m kind of (_kind of_) ok with the idea of a whitelist, but it makes jsxstyle slightly harder to explain and a bit more mysterious. I like that component props and style props have traded places. There’s a clear home for both. But that’s just, like, my opinion, man[. ](https://youtu.be/pWdd6_ZxX8c)If people are bumping into the props prop every day and it’s giving everyone heartburn, we can fix the problem quite easily.

**Comment by appsforartists** [comment]
Agreed that maintenance is the biggest challenge with a whitelist.

Incidentally, I've been using both jsxstyle and JSS lately - jsxstyle for static styles and JSS for dynamic ones.  I doubt you'd want to ship two CSS toolkits in a production app, but it's worked reasonably well for prototyping.  I'd stopped using jsxstyle for a period, because it didn't perform well during animations.  JSS allows you to modify styles without rerendering the tree, which fixed that problem.  It also consumes Observables, which is how I model animation anyway.

Bringing this up because _styles as fast as I can think_ nicely captures what I like about jsxstyle, and JSS is why I also use `className`.

**Comment by meyer** [comment]
closing for now
